### ISSUE TITLE
tmp directory is not automatically created so vagrant up fails

### ISSUE THREAD

**Issue by timcorkerton** [hashbangcode/vlad#167] opened 2015-03-07 10:20 UTC
TASK: [base | ensure directory /var/www/site/vlad_aux/tmp exists] ************* 
failed: [vlad-test] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1425723510.44-2398421295875/file", line 1993, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1425723510.44-2398421295875/file", line 278, in main
    os.mkdir(curpath)
OSError: [Errno 2] No such file or directory: '/var/www/site/vlad_aux/tmp'

**Comment by danbohea** [comment] 2015-03-07 10:36
Hi Tim.

That's odd - would you mind posting back here with the output of the following command run from your host box?

```
echo "VirtualBox `VBoxManage --version`"; vagrant --version; ansible --version; vagrant plugin list
```

**Comment by danbohea** [comment] 2015-03-07 10:36
Could you also provide the contents of the settings file that you're using?

**Comment by timcorkerton** [comment] 2015-03-07 21:18
see command output after settings file

settings ...
---
#  _________________________
# < Vlad configuration file >
#  -------------------------
#         \   ^__^
#          \  (oo)\_______
#             (__)\       )\/\
#                 ||----w |
#                 ||     ||
#
# Change settings here to control how Vlad sets up your box.

# Webserver settings
  webserver_hostname: 'vlad.local'
  webserver_hostname_alias: 'www.{{ webserver_hostname }}'

# Vagrantfile configuration
  boxipaddress: "192.168.100.101"
  boxname: "vlad-test"
  host_synced_folder: "./docroot"

# Install components:
# - To install a component set it to true.
# - To leave a component out of the install set the value to false.

  adminer_install: true

  apache_install: true

  imagemagick_install: false

  mailcatcher_install: false

  memcached_install: false

  munin_install: false

  mysql_install: true

  node_install: false

  php_install: true

  pimpmylog_install: false

  redis_install: false

  ruby_install: false # Ruby is required by MailCatcher

  sendmail_install: false

  solr_install: false

  varnish_install: false # If you turn this off then make sure you set the http_port to be 80.

  xhprof_install: false

# Provision with custom role
  custom_provision: false

# HTTP port for the web server. If you choose to install Varnish then you might want to set this to "8080"
  http_port: 80

# HTTP port for the Varnish cache
  varnish_http_port: 80

# Administration email (used in instances when a server email is needed)
  admin_mail: 'corkerton@gmail.com'

# PHP Settings
# PHP Version, can be one of:
# - "5.3"
# - "5.4"
# - "5.5"
# - "5.6"
# Note that Ubuntu14 won't install < PHP5.4 so you'll get PHP5.5+
# Vlad will error when a version that isn't understood is used
  php_version: "5.5"

# php.ini settings
  php_memory_limit: 512M
  php_max_execution_time: 60
  php_post_max_size: 100M
  php_upload_max_filesize: 100M
  php_display_errors: On
  php_display_startup_errors: On
  php_html_errors: On
  php_date_timezone: Europe/London

# Install PECL uploadprogress
  php_pecl_uploadprogress: true

# PHP APC Settings
  apc_rfc1867: '1'
  apc_shm_size: '256M'
  apc_shm_segments: '1'
  apc_num_files_hint: '0'

# MySQL Settings
  mysql_port: 3306
  mysql_root_password: sdfds87643y5thgfd
  server_hostname: vlad
  dbname: vladdb
  dbuser: vlad
  dbpass: wibble

# MySQL my.cnf settings
  mysql_max_allowed_packet: 128M
  innodb_buffer_pool_size: 128M
  innodb_file_per_table: true
  innodb_log_file_size: 128M
  mysql_character_set_server: utf8
  mysql_collation_server: utf8_general_ci
  skip_name_resolve: true

# SSH Settings
  ssh_port: 22
# Add RSA or DSA identity from host to guest on 'vagrant up'.
# Does not support identites that require a passphrase. Options include:
# false           : don't add anything
# true           : add default files  (~/.ssh/id_rsa, ~/.ssh/id_dsa & ~/.ssh/identity)
# "[filename]"  : add a specific file e.g. /Users/username/.ssh/[filename]
  use_host_id: false

# Varnish Settings
  varnish_memory: 512

# Drupal Solr integration
# Select which Solr module to install
# accepted values are 'search_api_solr' or 'apachesolr'
  drupal_solr_package: "apachesolr"

# Local hosts file location
# Default location on *nix hosts is '/etc/hosts'
# Default location for GasMask on OSX is '/Users/< username >/Library/Gas Mask/Local/< file >.hst'
  hosts_file_location: "/etc/hosts"

# Select whether Vlad should edit the hosts file.
  hosts_file_update: true

# Redis Port
  redis_port: 6379

# Set the level of verbosity that Ansible will use
# This can be one of "", "v", "vv", "vvv", or "vvvv"
  ansible_verbosity: ""

# Import MySQL database from file on 'vagrant up'. Options include:
# false          - don't import anything
# true          - import from vlad_aux/db_io/vlad_up.sql.gz
# "[filename]" - import from vlad_aux/db_io/[filename] (supports .sql, .bz2 and .gz files)
  db_import_up: false

# Add the default index.php file (useful to turn off if you are going git clone into the web root folder)
  add_index_file: true

# Git config user credentials (leave empty to skip this step)
  git_user_name: ""
  git_user_email: ""

# Use 'nfs' or 'rsync' for VM file editing in synced folder
  synced_folder_type: 'nfs'

# The OS that vlad will use. This can be:
# - "centos66"
# - "ubuntu12"
# - "ubuntu14"
  vlad_os: "ubuntu14"

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

$ echo "VirtualBox `VBoxManage --version`"; vagrant --version; ansible --version; vagrant plugin list
VirtualBox 4.3.10_Ubuntur93012
Vagrant 1.7.2
ansible 1.8.4
  configured module search path = None
vagrant-share (1.1.3, system)
vagrant-triggers (0.5.0)

**Comment by timcorkerton** [comment] 2015-03-07 21:25
So I created the tmp file manually and ran vagrant up again. It hung on nfs. So i restarted machine (host) and ran it again. It then successfully completed. 

Next issue is that the ip address maps to the default index.html file in html folder rather than the index.php in /var/www/site/docroot

**Comment by philipnorton42** [comment] 2015-03-07 21:39
Ok, so nfs seems to have been the problem there? I also sorted out the formatting of your update above.

Do you mean you are seeing the 'welcome to ubuntu' page, rather than the vlad default index.php file?
It sounds like your box didn't provision correctly, in which case you'll need to either run 'vagrant provision' to force a re-provision or 'vagrant destroy' to delete the box and 'vagrant up' to recreate it again.

Let me know how you get on.

**Comment by timcorkerton** [comment] 2015-03-07 23:07
Yes, i'm seeing the "welcome page" rather than the vlad php page.

I re-ran 'vagrant provision' and got the same result. i.e. seeing the index.html page 

The original issue obviously went away because the tmp dir exists

**Comment by philipnorton42** [comment] 2015-03-07 23:24
It's almost as if the Apache role hasn't completed successfully but has installed Apache.

Try destroying and rebuilding the box and see if that rectifies things.

**Comment by timcorkerton** [comment] 2015-03-10 11:09
tried it twice and getting exactly the same thing

**Comment by danbohea** [comment] 2015-03-10 11:10
What OS are you running on the host Tim?

**Comment by timcorkerton** [comment] 2015-03-10 11:13
ubuntu 14.04 LTS

**Comment by mbarcia** [comment] 2015-03-10 12:00
This maybe caused by vlad_aux folder not being present in the host (at the same level as vlad and Vagrantfile). Once created, it stays there, making it difficult to spot if you don't start fresh.

I added a line to the Vagrantfile to fix this. See after the comment, it creates the folder if not already present.
 
```ruby
    # Setup auxiliary synced folder

    FileUtils.mkdir_p vconfig['aux_synced_folder'] if !File.exist?(vconfig['aux_synced_folder'])
    config.vm.synced_folder vconfig['aux_synced_folder'], "/var/www/site/vlad_aux", 
```

**Comment by danbohea** [comment] 2015-03-10 12:03
The VagrantFile should already handle creation of the vlad_aux if it's not already there:

```
# Setup auxiliary synced folder
    config.vm.synced_folder vconfig['aux_synced_folder'], "/var/www/site/vlad_aux", type: "rsync", create: true, id: "vagrant-aux"
```

**Comment by mbarcia** [comment] 2015-03-10 12:28
Dan, good point, and the [docs](http://docs.vagrantup.com/v2/synced-folders/basic_usage.html) say so too. However, given this, and the problem I had, and also [this bug recently reported in Vagrant] (https://github.com/mitchellh/vagrant/issues/5317), I'd think the `create` param applies to the guest folder, not to the host folder.

**Comment by danbohea** [comment] 2015-03-10 12:37
Righto. Sounds like we may need to do some extra checks & possible directory creation in the VagrantFile then (which I'm guessing is what the snippet you posted above does) - at least until the possible Vagrant bug is fixed.

Odd that we've not seen this before though. I don't get this problem on OS X so perhaps it's host OS related?

Mariano, would you mind adding that amend to a PR so that we can test this?

**Comment by mbarcia** [comment] 2015-03-10 12:54
Dan, 
I will issue a PR, sure. However, you should be able to reproduce this right? If @timcorkerton is running VLAD on a OSX host and your Vagrant version match with his (1.7.2), the way to reproduce it would be
1. checkout the dev version in a new folder in OSX, 
2. copy the settings file pasted above, 
3. run `vagrant up`,
4. see if vlad_aux gets created in the host... (I know it doesn't get created in Windows).
It would be great if you can do this check, as this issue _maybe_ critical.

**Comment by danbohea** [comment] 2015-03-10 12:55
@timcorkerton is running Ubuntu 14.04 LTS

**Comment by mbarcia** [comment] 2015-03-10 13:02
Oh, right. I have an Ubuntu machine, will try to replicate it there. BTW, a PR for this change would break the windows/dev merge again, so let's wait until Phil merges windows into dev, which should happen very soon.

**Comment by mbarcia** [comment] 2015-03-10 17:32
I've tested on Ubuntu 14.10, Vagrant 1.7.2 (and also 1.6.3) and the vlad_aux folder does get created in the host. To confirm this, please @timcorkerton check the date of the vlad_aux folder (should be newer than the checked-out code).

**Comment by philipnorton42** [comment] 2015-03-13 12:28
Hi @timcorkerton. I've been persisting at this and actually found out what is going on!

It turns out that the default site that apache creates wasn't being turned off correctly in ubuntu14 and as such it would intercept the request for the site. This only happened under certain conditions though (which I can't quite figure out) so most people won't notice it. The fix for this is currently in dev but I might push a new release today/tomorrow as this might be a pain for other people.

To get around this currently you will need to disable the apache default site:

    sudo a2dissite 000-default.conf

And then reload the apache configuration:

    sudo service apache2 reload

Thanks for persisting with this. I appreciate the effort :)

**Comment by timcorkerton** [comment] 2015-03-13 12:41
Hi @philipnorton42. Thanks! That's great news. I haven't had time to pursue this further but was planning to look at it again at the weekend. I'll let you know how I get on. 

I'm also interested in testing the windows functionality as I work in a mix of ubuntu and windows environments and it would be fantastic to have a coherent approach to development.

**Comment by philipnorton42** [comment] 2015-03-13 13:08
Awsome :+1: 

If you are interested in Windows development then we have an issue for that :)
https://github.com/hashbangcode/vlad/issues/75

(good luck!)

**Comment by timcorkerton** [comment] 2015-03-14 15:26
OK, Thanks everyone. I can confirm the dev version does work on ubuntu 14.04, with the default site auto disabled and the vlad site enabled by default.

Have yet to try enabling anything but the default. I've got a project that is running varnish, reddis solr and I need to use xdebug so i'll keep you posted how that goes.

**Comment by philipnorton42** [comment] 2015-03-16 15:29
That's great news Tim. I've been away from the internet all weekend and so I didn't get a chance to push a new version. So today I've pushed version 1.0.4, which also contains the fix to your issue. I'm going to close this issue now, but if you find any more issues then please open a new issue :)

**Closed by philipnorton42** 2015-03-16 15:29 UTC
