### ISSUE TITLE
"Adjusting Vagrant environment and re-initializing" feedback on irrelevant commands

### ISSUE THREAD

**Issue by danbohea** [hashbangcode/vlad#335] opened 2016-02-04 13:49 UTC
```
Adjusting Vagrant environment and re-initializing
```

This feedback is triggered by a lot of commands now, `vagrant ssh` for one when I'm not sure that it's relevant. Can we tweak the Vagrantfile to only fire this feedback when it is relevant?

**Comment by zxaos** [comment] 2016-02-04 14:52
vagrant ssh needs to be re-initialized so it can find the VM and key (which are in the .vagrant folder).

However, at this why don't we just drop the output completely? The information presented doesn't actually _tell_ anyone anything, and I haven't seen any reports of problems caused by it...

**Comment by danbohea** [comment] 2016-02-04 15:02
> vagrant ssh needs to be re-initialized so it can find the VM and key (which are in the .vagrant folder).

Good point :) But yes, let's drop the output as it's likely more distraction than informative.

**Comment by zxaos** [comment] 2016-02-04 15:03
Sounds good. I'll squash the duplicate "found settings at..." notice while I'm at it.

**Comment by zxaos** [comment] 2016-02-04 15:11
Fixed by https://github.com/hashbangcode/vlad/commit/8ad432607b793c7e96f5a6d708080be1918d8abe

**Comment by danbohea** [comment] 2016-02-04 15:11
Good man!

**Closed by zxaos** 2016-02-04 15:11 UTC
Labels: bug
