### ISSUE TITLE
composer.sh fails with mode="a+x" but works with  mode ="755"

### ISSUE THREAD

**Issue by tweevick** [hashbangcode/vlad#215] opened 2015-04-24 15:32 UTC
Hello I'm new to git and vlad,
In composer.yml is writtent: mode="a+x ->this fails for me, but changing to mode ="755" works
- name: composer | add Composer shared vendor directory to path
  template:
    src=composer.j2
    dest=/etc/profile.d/composer.sh
    mode="a+x"
  tags: composer
  sudo: true
Error message
2015-04-24 16:22:05,703 p=16448 u=peter |  failed: [vlad] => {"details": "invalid literal for int() with base 8: 'a+x'", "failed": true, "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/etc/profile.d/composer.sh", "size": 201, "state": "file", "uid": 0}
2015-04-24 16:22:05,703 p=16448 u=peter |  msg: mode needs to be something octalish

**Comment by philipnorton42** [comment] 2015-04-24 15:38
Hi @tweevick, thanks for posting :)

If you could run the following command and print the output then I can make sure we are on the same page. One or two problems recently have come from differences in software versions so this is a quick way of finding out your current setup and perhaps replicating.

    echo "VirtualBox `VBoxManage --version`"; vagrant --version; ansible --version; vagrant plugin list

For more information on this command see our doc site: http://vlad-docs.readthedocs.org/en/latest/contributing/submitting_issues/

Thanks!

**Comment by mbarcia** [comment] 2015-04-24 15:38
Which version of ansible are you using? I think it needs to be 1.8+.

**Comment by keithcrooks** [comment] 2015-04-24 15:45
I've experienced this problem today too but only on my work Mac Mini but don't get it on my personal MacBook Pro or a friends MacBook Pro.

On the one it's failing on, the above command outputs the following:

VirtualBox 4.3.6r91406
Vagrant 1.6.5
ansible 1.7.2
vagrant-hostsupdater (0.0.11)
vagrant-login (1.0.1, system)
vagrant-share (1.1.3, system)
vagrant-triggers (0.5.0)

The one that works is:

VirtualBox 4.3.26r98988
Vagrant 1.6.5
ansible 1.9.0.1
 configured module search path = None
vagrant-cachier (1.2.0)
vagrant-hostsupdater (0.0.11)
vagrant-login (1.0.1, system)
vagrant-share (1.1.3, system)
vagrant-triggers (0.5.0)

I'll try to update ansible on my work machine and see if that helps.

**Comment by philipnorton42** [comment] 2015-04-24 15:50
I would upgrade ansible as a first cause of action. This can be done using:

    sudo pip install --upgrade ansible

Be careful though as there is currently a problem with Ansible 1.9 and the Solr role in Vlad. If you want to install a compatible version then you can do the following:

    sudo pip uninstall ansible
    sudo pip install ansible==1.8.4

If you aren't using Solr then it doesn't matter much :)

**Comment by keithcrooks** [comment] 2015-04-24 15:52
I'm not using Solr at the moment I'm just integrating VLAD into a simple existing project for evaluation purposes.

It's looking good so far and I think it fits our needs exactly.

If that's the case then going forward I will need to use Solr so thanks for the heads up!

**Comment by keithcrooks** [comment] 2015-04-24 16:09
You were right, it was the ansible version.

I've upgraded to 1.8.4 and it provisions fine now.

Thanks.

**Comment by philipnorton42** [comment] 2015-04-24 16:12
That's good news. I think what we need really is some way of forcing a minimum Ansible version. We already do the same for Vagrant and it should solve any errors like this for first time users.

**Comment by danbohea** [comment] 2015-05-03 11:47
> I think what we need really is some way of forcing a minimum Ansible version.

This issue requires the opposite - a maximum Ansible version (at least until we can address the root cause). But yes, there are probably other issues that would not pop up if we enforced a minimum too. So we need an upper and lower version :)

It looks like this is all possible via Ansible itself: https://github.com/ansible/ansible/pull/6619

**Comment by philipnorton42** [comment] 2015-05-05 20:32
I've added the check to detect Ansible under version 1.8.4. I did contemplate a maximum version but I think having a minimum version is a must, where as a maximum version only counts whilst there are bugs we can't fix or a certain version breaks Vlad. I've sorted the Solr issue so all we need to do is roll this update.

**Comment by danbohea** [comment] 2015-05-05 22:15
Yay. Avoiding a max version is certainly the way to go if we can :)

**Comment by philipnorton42** [comment] 2015-05-09 20:16
This version enforcement is now in a full release so I'm going to close this now.

**Closed by philipnorton42** 2015-05-09 20:16 UTC
Labels: enhancement
