### ISSUE TITLE
TASK: [solr | copy Solr instance] - failed

### ISSUE THREAD

**Issue by danylevskyi** [hashbangcode/vlad#212] opened 2015-04-21 08:52 UTC
Vlad version: 1.1.0

VirtualBox 4.3.26r98988
Vagrant 1.7.2
ansible 1.9.0.1
  configured module search path = None
vagrant-cachier (1.2.0)
vagrant-hostsupdater (0.0.11)
vagrant-share (1.1.3, system)
vagrant-triggers (0.5.0)

Settings:
vlad_os: 'buntu12'
rupal_solr_package: 'apachesolr'

```
failed: [test] => (item=bin) => {"changed": true, "cmd": ["cp", "-ar", "/home/vagrant/solr-4.7.2/example/solr/bin", "/home/solr"], "delta": "0:00:00.002708", "end": "2015-04-21 08:44:00.061080", "item": "bin", "rc": 1, "start": "2015-04-21 08:44:00.058372", "warnings": []}
stderr: cp: cannot overwrite non-directory `/home/solr' with directory `/home/vagrant/solr-4.7.2/example/solr/bin'
failed: [test] => (item=collection1) => {"changed": true, "cmd": ["cp", "-ar", "/home/vagrant/solr-4.7.2/example/solr/collection1", "/home/solr"], "delta": "0:00:00.003286", "end": "2015-04-21 08:44:00.248799", "item": "collection1", "rc": 1, "start": "2015-04-21 08:44:00.245513", "warnings": []}
stderr: cp: cannot overwrite non-directory `/home/solr' with directory `/home/vagrant/solr-4.7.2/example/solr/collection1'
```

**Comment by philipnorton42** [comment] 2015-04-21 08:55
I'm just wondering if:

      vlad_os: 'buntu12'

Should be

      vlad_os: 'ubuntu12'

and if that could be causing the above error? If it is then it might be worth adding a quick check for valid values on this parameter.

**Comment by danylevskyi** [comment] 2015-04-21 09:29
Just created a new box with minimum changes of the default settings and valid vlad_os: ubuntu12.
Got the same error.

**Comment by philipnorton42** [comment] 2015-04-21 09:30
Ok, thanks for checking. I'll get looking at this asap.

**Comment by danbohea** [comment] 2015-04-21 09:31
I'd also double check `rupal_solr_package: 'apachesolr'`. Should that read `drupal_solr_package: 'apachesolr'`?

**Comment by philipnorton42** [comment] 2015-04-21 09:34
That setting should at least default to 'apachesolr' though.

**Comment by philipnorton42** [comment] 2015-04-21 09:55
Unfortunately, I was unable to replicate the issue. Your error would suggest that the task 'copy Solr instance' hasn't run correctly, which then caused errors downstream. My setup is slightly different to yours (see below) so I'm going to try updating some stuff and see how it goes.

VirtualBox 4.3.16r95972
Vagrant 1.6.5
ansible 1.8.2
  configured module search path = None
vagrant-cachier (1.2.0)
vagrant-hostsupdater (0.0.11)
vagrant-login (1.0.1, system)
vagrant-share (1.1.3, system)
vagrant-triggers (0.5.0)

**Comment by danylevskyi** [comment] 2015-04-22 05:50
I downloaded a tarball with Vlad 1.1.0. Made a single change to settings.yml - solr_install: true.
Got the same error. Could anyone test it with Vagrant 1.7 and ansible 1.9?
I'll try to replicate the error on my laptop today.

**Comment by danbohea** [comment] 2015-04-22 10:55
I too can't recreate this with the following setup.

VirtualBox 4.3.26r98988
Vagrant 1.6.4
ansible 1.8.4
  configured module search path = None
vagrant-cachier (1.2.0)
vagrant-hostsupdater (0.0.11)
vagrant-login (1.0.1, system)
vagrant-share (1.1.3, system)
vagrant-triggers (0.5.0)

I'm provisioning another mac later this week which will be running latest version of Ansible & Vagrant so will test again then.

**Comment by xaviemirmon** [comment] 2015-04-22 13:26
@danylevskyi I have had a similar issue but was able to track it down to the latest version of Ansible.  After I ran:

`sudo pip uninstall ansible`

and 

`sudo pip install ansible==1.8.4` it started working for me.

**Comment by philipnorton42** [comment] 2015-05-13 10:30
Is this still an issue @danylevskyi ? I've not been able to replicate it.

**Comment by philipnorton42** [comment] 2015-06-11 21:38
After not being able to replicate this I'm going to close this issue under the assumption that it was caused by a bug in ansible. Please reopen it if you feel this is in error :)

**Closed by philipnorton42** 2015-06-11 21:38 UTC
Labels: bug
